config/routes.rb
Citysandbox::Application.routes.draw do

  resources :betausers

  root :to => 'home#splash', :as => :home

  get "welcome/show"
  match "welcome/show" => "welcome#show"
  get 'welcome/autocomplete_category_name'
  get "questions/autocomplete_category_name"
  match 'ugh' => 'welcome#show'
  scope :as => :home do
    get  '/' => 'home#splash', :as => :splash
    get '/login' => 'sessions#new', :as => :login
    get '/logout' => 'sessions#destroy', :as => :logout
    get '/register' => 'betausers#new', :as => :betaregister
  end

  resources :sessions

  resources :categories

  resources :groups do
    get '/members' => "groups#members"
    get '/project' => "groups#project"
    get '/edit' => "groups#edit"
  end

  match '/users/validate' => 'users#validate'
  match "/vote" => "proposals#vote"
  match "/edit_profile" => "users#edit"
  match "/follow" => "discussion#follow"
  match "/unfollow" => "discussion#unfollow"
  match "/recent" => "users#recent"
  match "/qr" => 'discussion#qr'
  match "/validate" => 'users#validate'
  match "/users/profile/:id" => 'users#profile'
  match "fetch" => "discussion#filter"
  match "ugh" => "questions#auto"
  
  match '/groups/members' => "groups#members"
  match '/groups/project' => "groups#project"
  match '/groups/edit' => "groups#edit"
  
  resources :questions do
    match "/auto" => "questions#auto"
    resources :response_questions, :shallow => true
    resources :challenges, :shallow => true
    resources :events, :shallow => true
    get :auto_complete_for_category_name, :on => :collection
    get :auto_complete_category_name, :on => :collection
  end
  resources :challenges do
      get :auto_complete_for_category_name, :on => :collection
      get :auto_complete_category_name, :on => :collection
  end
  
  post "questions/auto_complete_for_category_name" => "questions#auto_complete_for_category_name"
  post "challenges/auto_complete_for_category_name" => "challenges#auto_complete_for_category_name"
  post "events/auto_complete_for_category_name" => "events#auto_complete_for_category_name"
  get "questions/autocomplete_category_name"
  get "events/autocomplete_category_name"
  get "challenges/autocomplete_category_name"

  resources :events do
    resources :response_events, :shallow => true
    get :auto_complete_for_category_name, :on => :collection
    get :auto_complete_category_name, :on => :collection
  end

  resources :discussion do
    get '/' => 'discussion#summary', :as => :summary
  end

  match 'filter' => 'discussion#filterNew'

  get '/summary' => 'discussion#summary', :as => :summary

  match "/map" => 'map#index', :as => :map
  match "/map/draw_map" => 'map#draw_map'
  match "/map/draw" => "map#draw"

  match "messages/sent" => "sent#show"
  match "messages/inbox" => "inbox#show"
  match "messages/new" => 'inbox#new'
  match "messages/create" => "inbox#create"

  match "messages/reply/:id" => "inbox#respond", :as => :reply
  match "messages/send_to/:id" => "inbox#send_to", :as => :reply

  resources :users, :messages,  :inbox

  match "questionNew" => "questions#newForm"
  match "challengeNew" => "challenges#challengeNew"
  match "eventNew" => "events#eventNew"
  match "confirm" => "map#drawMapConfirm"
  match "map2" => "map#drawMapBoxies"
  

end

app/models/question.rb
 class Question < ActiveRecord::Base
  has_many :challenges
  belongs_to :user
  attr_accessor :most_recent, :lat, :lng, :anonymous
  acts_as :item_template, :as => :producible


    scope :has_category,       lambda{ |n| { :conditions => { :categories_id => n}}}
    scope :has_title, lambda{|name| {:conditions => ["title LIKE ? OR title LIKE ? OR title LIKE ?", "% " + name + " %", name, name + " %"]}}

    scope :start_from, lambda{|start| {:conditions => ["id >= ?", start]}}
    scope :keyword_sort, lambda{|key| {:conditions => ["title LIKE ? OR "]}}
    
    scope :followed, lambda{|key| {:conditions => {:id => key}}}
    
    scope :recent_than, lambda{|key| {:conditions => ["updated_at > ?", key]}}
    scope :order_by_followed, {:order => "id IN (SELECT COUNT(*) FROM 'followed_questions' WHERE 'followed_questions'.'question_id' = id)"}
    
    scope :popularity_contest, {:order => "id IN (SELECT COUNT(*) FROM 'followed_questions' WHERE 'followed_questions'.'question_id' = id) + id IN (SELECT COUNT(*) FROM 'response_questions' WHERE 'response_questions'.'question_id' = id)"}
    
    scope :response_contest, {:order => "id IN (SELECT COUNT(*) FROM 'response_questions' WHERE 'response_questions'.'question_id' = id)"}
    
    scope :keyword, lambda{|key| {:conditions => ["title LIKE ? OR title LIKE ? OR title LIKE ? OR description LIKE ? OR description LIKE ? OR description LIKE ?", "% " + key + " %", key, key + " %", "% " + key + " %", key, key + " %" ]}}
    
    @ft = @ft

	def generate_content
		return {"anonymous?"=>anonymous?}
	end
	
	def user
	  ItemTemplate.where(:user_id => self.user_id).where(:producible_id => self.id)
  end
      
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  autocomplete :category, :name
  size_limit_questions = 15
  size_limit_discussion = 5
  page_offset = 1
  auto_complete_for :category, :name
  # GET /questions/1
  # GET /questions/1.json
  def show
    if current_user == nil
      redirect_to home_login_url
    else
      @question = Question.where(:id => params[:id])[0]
      @user = User.where(:id => @question.user_id).first
      if @user == nil
        @user = User.where(:id => 15).first
      end
      @categories = @question.categories
      
       @sample = Question.all.pop
        @samples = @sample.kludgy_related_similar()
        @different_samples = sample.kludgy_related_other()

  #    @followed = current_user.followed_questions.where(:question_id => params[:id]).size != 0
      #@followed_user = current_user.followed_users.where(:followed_user_id => @question.user_id).size != 0

     # @num_events = 0
    #  @question.challenges.each { |challenge|
     #   @num_events += challenge.events.length
     # }
     puts 'do we play by the same rules brah?'
     @q = @question
     if @q.nil?
       @resp_id = nil
     else
     @resp_id = @q.id
     @responses = ResponseTemplate.where(:item_id => @q.producible_id).where(:parent_id => nil)
     end
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @question }
      end
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new
    @category = Category.new
    @sample = Question.all.pop
    @samples = @sample.kludgy_related_similar()
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  def auto
@categories = Category.find(:all,:conditions => ['name LIKE ?', "#{params[:q]}%"],  :limit => 5, :order => 'name')
respond_to do |format|
format.html # auto.html.erb
format.xml  { render :xml => @cities }
format.js # auto.js.erb
format.json { render :json => @cities }
end

end

  def newForm
    @question = Question.new
    @category = Category.new
    @categories = Category.all
     @sample = Question.all.pop
      @samples = @sample.kludgy_related_similar()
    puts "BLEEP BLOOP BLEEP BLEEP"
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    puts "WORK IT GURL"
    @question = Question.new(params[:question])
    @question.user_id = current_user.id
    geocode = Geocoder.coordinates(@question.location)
    @question.lat = geocode[0].to_s
    @question.lng = geocode[1].to_s
    respond_to do |format|
      if @question.save
        @question.insert_location(@question.lat + ', ' + @question.lng)
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :ok }
    end
  end


  def prefetch
    size_limit_questions = 15
    size_limit_discussion = 5
    page_offset = 1
    @questions = Question.find(:all, :offset => page_offset * size_limit_questions, :limit =>size_limit_questions)
    @discussion_next = []
    @questions.each {|x|  @discussion_next = @discussion_next + [ResponseQuestion.where(:question_id => x.id).limit(size_limit_discussion)]}

  end

  def filter_by_category
    @questions = Question.where(:category => category_to_sort).limit(size_limit_questions).offset(size_limit_questions*page_offset)
    @discussion_next = []
    @questions.each{|x| @discussion_sets = @discussion_sets + ResponseQuestion.where(:question_id => x.id).limit(size_limit_discussion)}
  end


  def filter_by_set_definition
  end

  def auto
     if params[:q]
    @categories = Category.all(:conditions => ["name like ?", params[:q] + '%'])
  else
    @categories = Category.all
  end

  respond_to do |wants|
    wants.html
    wants.js
  end

  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_newRegister.html.erb
       <%= form_for @question, :action => :create, :controller => :questions do |f| %>
     <% if @question.errors.any? %>
       <div id="error_explanation">
         <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
         <ul>
         <% @question.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
         </ul>
       </div>
     <% end %>
     <p>
       <%= f.hidden_field :lat %>
       <%= f.hidden_field :lng %>
       <%= f.label :title %> <font size='1px'>(Character Limit: 255)</font>
       <br>
       <%= f.text_area :title, :rows=>2 %>
     </p>
     <p>
       <%= f.label :location %> <font size='1px'>(Character Limit: 100)</font>
       <br>
       <%= f.text_area :location, :rows=>1, :placeholder=>"" %>
       <br>
       <br>
       <br>
       <div id="form_map_canvas"></div>
     </p>
     <p>
       <%= f.label :description %> <font size='1px'>(Character Limit: 800)</font>
       <br>
       <%= f.text_area :description, :rows=>3 %>
     </p>
     <p>
       <%= f.label "Upload a picture:" %>
       <%= f.file_field :picture %>
     </p>
     <p>
       <%= f.check_box :anonymous %>
       <%= f.label 'Post anonymously' %>
     </p>
	<%= submit_tag 'Create Your Question', :class => 'btn' %>
     <p>
       <%= f.label 'Categories' %>
       <br>

		<%= form_tag("/categories", :method => 'post') do %>
	 <% autocomplete_field_tag 'category', '', questions_autocomplete_category_name_path, :size => 75 %>
		<% end %>
     </p>

<br>  <br>  <br>  <br>  <br>
   <% end %>

app/views/questions/_response_tree.html.erb
	<dl class="response_list">
		<% @responses.each do |response| %>
		<dt> 
			<%= response.score %>
			<img src="../oldfrontend/upboat.png" align="left"/>
			<%= response.user.name %> 
		</dt>
			<dd> 
				<%= response.response %>
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Permalink</a>&nbsp;&nbsp;<a href="#">Reply</a>
			</dd>
			
		 <% end %>
		
	</dl>

app/views/questions/auto.html.erb
<% content_for :head do %>
<%= javascript_include_tag 'jquery-1.2.6.min', 'jquery.ui-1.6rc2/ui/minified/ui.core.min', 'jquery.ui-1.6rc2/ui/minified/ui.autocomplete.min' %>
<%= stylesheet_link_tag 'jquery.ui-1.6rc2/themes/default/ui.all' %>
<script type="text/javascript">
$(document).ready(function(){
jQuery.ajaxSetup({
'beforeSend': function(xhr) {xhr.setRequestHeader("Accept", "text/javascript")}
})
$("#q").autocomplete( {
url : "ugh",
mustMatch : false
}
);
$("#q").autocomplete('result', function(event, data, formatted) {
if (data)
document.location.href = '/categories/' + data[1];
});
});
</script>

<% end %>
There is
<% form_tag 'ugh', :method => 'get' do %>
<%= text_field_tag :q, params[:q] %>
<%= submit_tag "Locate category", :name => nil %>
<% end %>
UGHHHHHH

app/views/questions/auto.js.erb
<% for categories in @categories %>
<%= category.name %>, |<%= city.id %>
<% end %>

app/views/questions/auto.js.haml
# auto.js.haml
= render :text => @categories.map(&:name)

app/views/questions/dummyForm.erb
       <%= form_for @question, :action => :create, :controller => :questions do |f| %>
     <% if @question.errors.any? %>
       <div id="error_explanation">
         <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
         <ul>
         <% @question.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
         </ul>
       </div>
     <% end %>
     <p>
       <%= f.hidden_field :lat %>
       <%= f.hidden_field :lng %>
       <%= f.label :title %> <font size='1px'>(Character Limit: 255)</font>
       <br>
       <%= f.text_area :title, :rows=>2 %>
     </p>
     <p>
       <%= f.label :location %> <font size='1px'>(Character Limit: 100)</font>
       <br>
       <%= f.text_area :location, :rows=>1, :placeholder=>"" %>
       <br>
       <br>
       <br>
       <div id="form_map_canvas"></div>
     </p>
     <p>
       <%= f.label :description %> <font size='1px'>(Character Limit: 800)</font>
       <br>
       <%= f.text_area :description, :rows=>3 %>
     </p>
     <p>
       <%= f.label "Upload a picture:" %>
       <%= f.file_field :picture %>
     </p>
     <p>
       <%= f.check_box :anonymous %>
       <%= f.label 'Post anonymously' %>
     </p>
     <p>
       <%= f.label 'Categories' %>
       <br>
       <%= form_for @category do |f| %>
       <%=  f.autocomplete_field :name, questions_autocomplete_category_name_path %>
       <% end %>
     </p>
	<%= submit_tag 'Create Your Question', :class => 'btn' %>
<br>  <br>  <br>  <br>  <br>
   <% end %>

app/views/questions/formOld.erb
<script type="text/javascript">
$(document).ready( function() {
	$('#related_content').stickySidebar();
	
	$('#tabs ul').idTabs();
	
	
	var map;
    var myOptions = {
    	zoom: 14,
    	center: new google.maps.LatLng(37.87159260,-122.2727470), // Berkeley, CA
    	mapTypeId: google.maps.MapTypeId.ROADMAP
	};
   	map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);

    var geocoder = new google.maps.Geocoder();
	var address = $.trim(address = $('#question_location').val().replace(/[\t\n\r]/gi, " "));
	    geocoder.geocode( { 'address': address}, function(results, status) {
	      if (status == google.maps.GeocoderStatus.OK) {
	        map.setCenter(results[0].geometry.location);
	        var marker = new google.maps.Marker({
	            map: map,
	            position: results[0].geometry.location,
				icon: '../images/question_map_icon.png'
	        });
	      }
	});

	$('#challenge_location').blur( function() {
		var challenge_geocoder = new google.maps.Geocoder();
		var challenge_address = $.trim(challenge_address = $('#challenge_location').val().replace(/[\t\n\r]/gi, ""));
		    geocoder.geocode( { 'address': challenge_address}, function(results, status) {
		      if (status == google.maps.GeocoderStatus.OK) {		      
				$('#challenge_lat').attr('value', results[0].geometry.location.lat());
				$('#challenge_lng').attr('value', results[0].geometry.location.lng());
		      }	
		});
	});	
	
	$('#challenge_categories_id').attr('value', '<%= @question.categories_id %>');
	$('#challenge_location').attr('value', address);
	
	$('#share').attr('href', 'mailto:?subject=[City%20Sandbox]%20<% current_user.login%>%20has%20shared%20a%20link%20with%20you!&body=<%=question_url(@question)%>');
	
	$('#unfollow_user').click(function(){
		var params = {};
		params['item_to_follow'] = '<%= @question.user.id %>';
		params['type'] = 'User';
		$.get('/unfollow', params);
		$('#unfollow_user').hide();
		$('#follow_user').show();
	});
	
	$('#follow_user').click(function(){
		var params = {};
		params['item_to_follow'] = '<%= @question.user.id %>';
		params['type'] = 'User';
		$.get('/follow', params);
		$('#follow_user').hide();
		$('#unfollow_user').show();
	});
	
	$('#unfollow').click(function(){
		var params = {};
		params['item_to_follow'] = '<%= @question.id %>';
		params['type'] = 'Question';
		$.get('/unfollow', params);
		$('#unfollow').hide();
		$('#follow').show();
	});
	
	$('#follow').click(function(){
		var params = {};
		params['item_to_follow'] = '<%= @question.id %>';
		params['type'] = 'Question';
		$.get('/follow', params);
		$('#follow').hide();
		$('#unfollow').show();
	});
	
	if ('<%= @followed %>' == 'true') {
		$('#follow').hide();
	} else {
		$('#unfollow').hide();
	}
	if ('<%= @followed_user %>' == 'true') {
		$('#follow_user').hide();
	} else {
		$('#unfollow_user').hide();
	}

	$(window).resize(function() {
		$('#content').css('margin-left', ($(window).width()-960)/2 + 'px');
		$('#icon_title').css('margin-left', ($(window).width()-960)/2 + 'px');
		$('#user_nav').css('margin-right', ($(window).width()-960)/2 + 'px');
		$('#header_tabs').css('margin-left', ($(window).width()-960)/4 + 'px');
	});
	$('#content').css('margin-left', ($(window).width()-960)/2 + 'px');
	$('#icon_title').css('margin-left', ($(window).width()-960)/2 + 'px');
	$('.user_avatar').css('vertical-align', 'middle');
	$('#user_nav').css('margin-right', ($(window).width()-960)/2 + 'px');
	$('#header_tabs').css('margin-left', ($(window).width()-960)/4 + 'px');
	
	$('.event_individual hr').last().remove();
	
	$('.iframe').fancybox({
		'width' : 320,
		'height' : 350,
		'autoscale': false,
		'autoDimensions': false,
		'titlePosition': 'outside',
		'titleFormat': formatTitle
	});
	$('#fancybox-wrap').click(function () {
		printIframe('fancybox-frame');
	});
});
function printIframe(id)
{
    frames[0].print();
}
function formatTitle() {
    return '<div id="print"><a href="javascript:;"><img src="../images/print.png" title="Print QR Code."></a></div>';
}
</script>
<div id='content'>
<div id='user_sidebar'>
	<% if @question.anonymous != 1 %>
		<b>About <a href='/users/profile/<%= @question.user.id %>' class='black_link'><%= @question.user.login %></a> </b>
		<br>
		<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'100x100', :alt => "User avatar" %>
		<%= @question.user.picture %> 
		<br>
		<b>Joined:</b> <%= @question.user.created_at.strftime("%Y %b %d")%>
		<br>
		<b>Questions:</b> <%= @question.user.questions.length %>
		<br>
		<b>Responses:</b> <%= @question.user.response_questions.length + @question.user.response_challenges.length + @question.user.response_events.length %>
		<br>
		<b>Challenges:</b> <%= @question.user.challenges.length %>
		<br>
		<br>
		<!--<b><%= link_to 'Recent Activity', summary_path, :class=>'black_link' %></b>
		<br>-->
		<b><a href='/messages/send_to/<%=@question.user.id%>' class='black_link'>Send Message</a></b>
		<br>
		<b><a href='javascript:;' id='unfollow_user' class='black_link'>Unfollow</a></b>
		<b><a href='javascript:;' id='follow_user' class='black_link'>Follow</a></b>
	<% end %>
</div>
<div id='main_question_content'>
<div class='question_main'>
	<span id='question_map'>
		<div id="map_canvas"></div>
		<%=h @question.location %>
		<%= hidden_field(:question, :location) %>
	</span>
	<span id='question_title_display'>
		<b><%= @question.title %></b>
	</span>
	<br><br>
	<span id='question_author'>
		<% if @question.anonymous != 1 %>
		<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'30x30', :alt => "User avatar" %>
		<%=h @question.user.picture %> by <%= @question.user.login %> |
		<% else %>
		Anonymous | 
		<% end %>
		<%= @question.created_at.strftime("%Y %b %d") %> | <%= @category.category %> |
		<a href='javascript:;' id='unfollow' class='black_link'>Unfollow | </a> 
		<a href='javascript:;' id='follow' class='black_link'>Follow | </a> 
		<a href='' class='black_link' id='share'> Share </a> |
		<%= link_to 'QR', qr_url(:format=>question_url(@question), :title=>@question.title), :class=>'iframe black_link'%>
	</span>
	<br>
	<br>
	<div id='form_links'>
	<ul>
	<li><a href="#response_form" class="black_link" onclick='$("#responses_tab").click();'>Add Response</a></li>
	<li><a href="#challenge_form" class="black_link" onclick='$("#challenges_tab").click();'>Add Challenge</a></li>
	</ul>
	</div>
</div>
<% if @question.description.length > 0 %>
	<br>
	<div class='question_main'>
		<span id='question_description'>
			<%= @question.description %> 
		</span>
	</div>
<% end %>
<div id='tabs'>
<br>
<div id='tabs_menu'>	
<ul>
	<li><b><a href="#responses" id='responses_tab'>Responses</a></b></li>
	<li><b><a href="#challenges" id='challenges_tab'>Challenges</a></b></li>
	<li><b><a href="#events">Events</a></b></li>
</ul>
</div>
<div id='responses'>
<div class='tab_body'>
	<% @question.response_questions.reverse_each do |r| %>
	<div class='individual response_individual'>
			<% if r.anonymous == 1 %>
				<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'30x30', :alt => "User avatar" %>
				<%=h r.user.picture %> 
				Anonymous | 
			<% else %>
				<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'30x30', :alt => "User avatar" %>
				<%=h r.user.picture %> 
				<%=h r.user.login %> |
			<% end %>
			<%= time_ago_in_words(r.created_at) %> ago 
			<div class='latest_response'>
			    <%=h r.response %>
			</div>
		<br>
		<hr>
	</div>
	<% end %>
	<br>
	<div id='response_form'>
		Add Response
		<br>
		<%= form_for([@question, ResponseQuestion.new]) do |r| %>
		    <%= r.text_area :response, :rows => 3 %>
			<br>
			<%= r.check_box :anonymous %>
			<%= r.label 'Post anonymously' %>
			<br>
		    <%= r.submit "Submit" %>
		<% end %>
	</div>
</div>
</div>


<div id='challenges'>
<div class='tab_body'>
	<% @question.challenges.each do |e| %>
	<div class='individual challenge_individual'>
			<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'30x30', :alt => "User avatar" %>
			<%=h e.user.picture %> 
			<%=h e.user.login %> | 
			<%= time_ago_in_words(e.created_at) %> ago 
		<div class='entry_title'>
			<b><%= link_to e.title, e, :class=>'black_link' %></b>
		</div>
		<div id='ind_challenge_dates'>
			<ul>
				<li><b> Submission Deadline: </b> <%= e.submission_deadline.strftime("%Y %b %d") %> </li>
				<li><b> Vote Deadline: </b> <%= e.vote_deadline.strftime("%Y %b %d") %> </li>
			</ul>			</ul>
		</div>
		<div class='latest_response'>
		    <%=h e.description %>
		</div>
		<br>
		<hr>
	</div>
	<br>
	<% end %>

	<div id='challenge_form'>
		Add Challenge
		<br>
		<%= form_for [@challenge, Challenge.new] do |c| %>
		  <%= c.hidden_field :lat %>
		  <%= c.hidden_field :lng %>
		  <p>
		    <%= c.label :title, "Title" %>
			<br>
		    <%= c.text_field :title %>
		  </p>
			<%= c.hidden_field :question_id, :value => @question.id %>
		  <p>
		    <%= c.label :description, "Description" %>
			<br>
		    <%= c.text_area :description, :rows=>3 %>
		  </p>
		  <p>
			<%= c.label :location %>
			<br>
			<%= c.text_area :location, :rows=>2 %>
		  </p>
		  <p>
		    <%= c.label :submission_deadline, "Proposal Deadline" %><br />
		    <%= c.datetime_select :submission_deadline, :default=> 7.days.from_now %>
		  </p>
		  <p>
		    <%= c.label :vote_deadline , "Vote Deadline" %><br />
		    <%= c.datetime_select :vote_deadline, :default=> 14.days.from_now %>
		  </p>
		  <p>
			<%= c.label 'Categories: ' %>
			<br>
			<%= c.select(:categories_id, Categories.all.collect {|c| [ c.category, c.id] }, {:include_blank => 'Other'})%>
			<br>
		  </p>
		  <p>
		    <%= c.submit "Submit" %>
		  </p>
		<% end %>
</div>
</div>
</div>
<div id='events'>
<div class='tab_body'>
<% if @num_events == 0 %>
	<div class='individual event_individual'>
		There are no events for this question.
		<br>
		<br>
	</div>
<% else %>	
	<% @question.challenges.each do |challenge| %>
		<% challenge.events.each do |e| %>
		<div class='individual event_individual'>
				<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'30x30', :alt => "User avatar" %>
				<%=h e.user.picture %> 
				<%=h e.user.login %> | 
				<%= e.created_at.strftime("%Y %b %d") %>
			<div class='entry_title'>
				<b><%= link_to e.title, e, :class=>'black_link' %></b>
			</div>
			<div class='event_date'>
			<b> Date: </b> <%= e.time.strftime("%Y %b %d") %> </li>
			</div>
			<div class='latest_response'>
			    <%=h e.description %>
			</div>
			<br>
			<hr>
		</div>
		<% end %>
	<% end %>
<% end %>
</div>
</div>
</div>
<br>
<% if @question.user == current_user %>
	<%= link_to 'Edit', edit_question_path(@question), :class=>'black_link' %> |
<% end %>
<%= link_to 'Back To Summary', summary_path, :class=>'black_link' %>
</div>
</div>
</div>