config/routes.rb
Citysandbox::Application.routes.draw do

  resources :betausers

  root :to => 'home#splash', :as => :home

  get "welcome/show"
  match "welcome/show" => "welcome#show"
  get 'welcome/autocomplete_category_name'
  get "questions/autocomplete_category_name"
  match 'ugh' => 'welcome#show'
  scope :as => :home do
    get  '/' => 'home#splash', :as => :splash
    get '/login' => 'sessions#new', :as => :login
    get '/logout' => 'sessions#destroy', :as => :logout
    get '/register' => 'betausers#new', :as => :betaregister
  end

  resources :sessions

  resources :categories

  resources :groups do
    get '/members' => "groups#members"
    get '/project' => "groups#project"
    get '/edit' => "groups#edit"
  end

  match '/users/validate' => 'users#validate'
  match "/vote" => "proposals#vote"
  match "/edit_profile" => "users#edit"
  match "/follow" => "discussion#follow"
  match "/unfollow" => "discussion#unfollow"
  match "/recent" => "users#recent"
  match "/qr" => 'discussion#qr'
  match "/validate" => 'users#validate'
  match "/users/profile/:id" => 'users#profile'
  match "fetch" => "discussion#filter"
  match "ugh" => "questions#auto"
  
  match '/groups/members' => "groups#members"
  match '/groups/project' => "groups#project"
  match '/groups/edit' => "groups#edit"
  
  resources :questions do
    match "/auto" => "questions#auto"
    resources :response_questions, :shallow => true
    resources :challenges, :shallow => true
    resources :events, :shallow => true
    get :auto_complete_for_category_name, :on => :collection
    get :auto_complete_category_name, :on => :collection
  end
  resources :challenges do
      get :auto_complete_for_category_name, :on => :collection
      get :auto_complete_category_name, :on => :collection
  end
  
  post "questions/auto_complete_for_category_name" => "questions#auto_complete_for_category_name"
  post "challenges/auto_complete_for_category_name" => "challenges#auto_complete_for_category_name"
  post "events/auto_complete_for_category_name" => "events#auto_complete_for_category_name"
  get "questions/autocomplete_category_name"
  get "events/autocomplete_category_name"
  get "challenges/autocomplete_category_name"

  resources :events do
    resources :response_events, :shallow => true
    get :auto_complete_for_category_name, :on => :collection
    get :auto_complete_category_name, :on => :collection
  end

  resources :discussion do
    get '/' => 'discussion#summary', :as => :summary
  end

  match 'filter' => 'discussion#filterNew'

  get '/summary' => 'discussion#summary', :as => :summary

  match "/map" => 'map#index', :as => :map
  match "/map/draw_map" => 'map#draw_map'
  match "/map/draw" => "map#draw"

  match "messages/sent" => "sent#show"
  match "messages/inbox" => "inbox#show"
  match "messages/new" => 'inbox#new'
  match "messages/create" => "inbox#create"

  match "messages/reply/:id" => "inbox#respond", :as => :reply
  match "messages/send_to/:id" => "inbox#send_to", :as => :reply

  resources :users, :messages,  :inbox

  match "questionNew" => "questions#newForm"
  match "challengeNew" => "challenges#challengeNew"
  match "eventNew" => "events#eventNew"
  match "confirm" => "map#drawMapConfirm"
  match "map2" => "map#drawMapBoxies"
  

end

app/controllers/sent_controller.rb
class SentController < ApplicationController
  def index
     @messages = current_user.messages
   end

   def create
     @messages = current_user.messages
   end

   def new
     @messages = current_user.messages
   end

   def show
     @messages = current_user.messages
     
     if (params[:subject] != nil)
       b = Message.new
       b.user = current_user
       b.subject = params[:subject]
       b.body = params[:body]
       b.save
       msgCopy = MessageCopy.new
       msgCopy.message = b
       msgCopy.user = User.where(:login => params[:sendTo]).first
       msgCopy.save
     end
  end
    
    def special
      @messages = current_user.messages
    @success = "Progress? :D"
    end
    

end

app/helpers/sent_helper.rb
module SentHelper
end

app/views/sent/create.html.erb
<h1>Sent#create</h1>

<p> Is this good?
	</p>

app/views/sent/index.html.erb
<p>Hey look gaiz! </p>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
	<td>
	
		MESSAGES!
	</td>
	<tr>
		<%=h @messages.length %>
		</tr>
		<tr>
			First message <%=h @messages[0].subject%>
			</tr>
  </tr>

<% @messages.each do |x| %>
  <tr>
	<td>
	 Subject: <%=h x.subject %>
	</td>
	
	<td>
	 Body:	<%=h x.body %>
	</td>
	
	<td>
	User:	<%=h x.user.login %>
	</td>	




  </tr>
<% end %>
</table>

<%= link_to 'Send a message', 'sent/new' %>

app/views/sent/new.html.erb
<script type="text/javascript">

</script>
<style type="text/css">
#content {
	background-image: url("../../images/splash_box.png");
	background-position: center;
	background-repeat: no-repeat;
	height: 480px;
	width: 100%;
	text-align: center;
}
#message_form {
	color: #DDDDDD;
	line-height:2em;
	padding-top:20px;
}
</style>
<div id="content">
<div id='message_form'>
<form action= "create">
  Subject: <input type="text" name="subject" size="35"/><br />
  Body: <textarea name="body" rows="5" cols="35"> </textarea><br />
  Send To: <input type ="text" name="sendTo" size="35"><br />
  <input type="submit" value="Send Message"/>
</form>
</div>
</div>

app/views/sent/show.html.erb
<script type="text/javascript">
$(document).ready( function() {
	$('.response_individual hr').last().remove();
})
</script>
<style type="text/css">
.message_title {
	line-height: 2.5em;
}
</style>
<div id='content'>
<div id='user_sidebar'>
	<% if !current_user.nil? %>
		<b><%= current_user.login %>'s Sent Messages </b>
		<br>
		<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'100x100', :alt => "User avatar" %>
		<%= current_user.picture %> 
		<br>
		<b>Joined:</b> <%= current_user.created_at.strftime("%Y %b %d")%>
		<br>
		<b>Questions:</b> <%= current_user.questions.length %>
		<br>
		<b>Responses:</b> <%= current_user.response_questions.length + current_user.response_challenges.length + current_user.response_events.length %>
		<br>
		<b>Challenges:</b> <%= current_user.challenges.length %>
		<br>
		<br>
		<%= link_to 'Compose a Message', messages_new_path, :class=>'black_link' %>
		<br>
		<%= link_to 'Inbox', messages_inbox_path, :class=>'black_link' %>
		<br>
		<a href="/edit_profile" class="link_logout black_link">Edit Profile</a>
	<% end %>
</div>
<div id='main_question_content'>
<div id='responses'>
<div class='tab_body'>
	<% @messages.each do |msg| %>
		<% msg.message_copys.each do |x| %>
		<div class='individual response_individual'>
		<span class='message_title'>
		<b><%=h msg.subject %></b>
		</span>
		<br>
		<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'30x30', :alt => "User avatar" %>
		From: 
		<%=h msg.user.picture %> 
		<%=h msg.user.login %> |
		Sent: <%= msg.created_at.strftime("%Y %b %d")%>
		<br>
		<p>
			<%=h msg.body %>
		</p>
		<br>
		<hr>
		</div>
		<% end %>
	<% end %>
	<br>
</div>
</div>

</div>
</div>

app/views/sent/special.html.erb
<h1>Sent#special</h1>

<p> Is this good?
	<%=h @success%>

	 </p>