config/routes.rb
Citysandbox::Application.routes.draw do

  resources :betausers

  root :to => 'home#splash', :as => :home

  get "welcome/show"
  match "welcome/show" => "welcome#show"
  get 'welcome/autocomplete_category_name'
  get "questions/autocomplete_category_name"
  match 'ugh' => 'welcome#show'
  scope :as => :home do
    get  '/' => 'home#splash', :as => :splash
    get '/login' => 'sessions#new', :as => :login
    get '/logout' => 'sessions#destroy', :as => :logout
    get '/register' => 'betausers#new', :as => :betaregister
  end

  resources :sessions

  resources :categories

  resources :groups do
    get '/members' => "groups#members"
    get '/project' => "groups#project"
    get '/edit' => "groups#edit"
  end

  match '/users/validate' => 'users#validate'
  match "/vote" => "proposals#vote"
  match "/edit_profile" => "users#edit"
  match "/follow" => "discussion#follow"
  match "/unfollow" => "discussion#unfollow"
  match "/recent" => "users#recent"
  match "/qr" => 'discussion#qr'
  match "/validate" => 'users#validate'
  match "/users/profile/:id" => 'users#profile'
  match "fetch" => "discussion#filter"
  match "ugh" => "questions#auto"
  
  match '/groups/members' => "groups#members"
  match '/groups/project' => "groups#project"
  match '/groups/edit' => "groups#edit"
  
  resources :questions do
    match "/auto" => "questions#auto"
    resources :response_questions, :shallow => true
    resources :challenges, :shallow => true
    resources :events, :shallow => true
    get :auto_complete_for_category_name, :on => :collection
    get :auto_complete_category_name, :on => :collection
  end
  resources :challenges do
      get :auto_complete_for_category_name, :on => :collection
      get :auto_complete_category_name, :on => :collection
  end
  
  post "questions/auto_complete_for_category_name" => "questions#auto_complete_for_category_name"
  post "challenges/auto_complete_for_category_name" => "challenges#auto_complete_for_category_name"
  post "events/auto_complete_for_category_name" => "events#auto_complete_for_category_name"
  get "questions/autocomplete_category_name"
  get "events/autocomplete_category_name"
  get "challenges/autocomplete_category_name"

  resources :events do
    resources :response_events, :shallow => true
    get :auto_complete_for_category_name, :on => :collection
    get :auto_complete_category_name, :on => :collection
  end

  resources :discussion do
    get '/' => 'discussion#summary', :as => :summary
  end

  match 'filter' => 'discussion#filterNew'

  get '/summary' => 'discussion#summary', :as => :summary

  match "/map" => 'map#index', :as => :map
  match "/map/draw_map" => 'map#draw_map'
  match "/map/draw" => "map#draw"

  match "messages/sent" => "sent#show"
  match "messages/inbox" => "inbox#show"
  match "messages/new" => 'inbox#new'
  match "messages/create" => "inbox#create"

  match "messages/reply/:id" => "inbox#respond", :as => :reply
  match "messages/send_to/:id" => "inbox#send_to", :as => :reply

  resources :users, :messages,  :inbox

  match "questionNew" => "questions#newForm"
  match "challengeNew" => "challenges#challengeNew"
  match "eventNew" => "events#eventNew"
  match "confirm" => "map#drawMapConfirm"
  match "map2" => "map#drawMapBoxies"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_uniqueness_of :login, :email
  has_many :user_areas
  has_many :user_categories
  has_many :tagged_areas, :through => :user_areas
  has_many :categories, :through => :user_categories
  has_many :notifications
  has_many :sent_messages
  has_many :received_messages, :foreign_key => :received_by
  has_many :folders
  has_many :groups, :through => :memberships
  #has_many :response_templates
  has_many :item_templates, :through => :subscriptions
  #has_and_belongs_to_many :followees, 
	#					  :class_name=>"user",
	#					  :join_table => "user_subscriptions",
	#					  :foreign_key => "follower_id",
	#					  :association_foreign_key => "followee_id"

  validates :login, :presence => true
  validates :email, :presence => true
  validates :password, :presence => true
  validates :location, :presence => true
  #validate :name_check
  after_create :send_confirmation
  attr_accessible :upload
  
  def render_image(user)
    if user.picture != nil || user.picture != "DEFAULT"
      return Fleakr.resource_from_url(user.picture, 'rb') 	
    end
  end
  
  def upload_image(user, uploaded_file)
    name =  uploaded_file.original_filename
        
    #create the file path
    path = File.join("tmp", name)

    # write the file
    File.open(path, "wb") { |f| f.write(uploaded_file.read) }
        
    item = Fleakr.upload(path)
    user.picture = "DEFAULT"
    puts item
    if item != nil && item[0] != nil
        user.picture = item[0].url
        puts "THE FUCK"
        puts item[0].url
        user.save
    end
  end
  
  def my_followed
	return item_templates
  end
  
  def name_check
    #if(self.login.strip != login)
    #  errors.add(:login, "login can't start or end with blank spaces")
    #end
    #if(self.login.split.size != 1)
    #  errors.add(:login, "login can't have any spaces in it")
    #end
  end

  
  def unfollow_user(follow_user)
	followed = User_Subscription.where(:follower_id=>id).where(:followee_id=>follow_user)
	if followed != nil
	  followed.destroy
	end
  end
  
  def send_confirmation
    temp_pwd = :temp_pwd
    mail = UserMailer.signup_notification(self, self.temp_pwd)
    mail.deliver
  end
  def recent_activity
    stuff = []
    stuff += Item_templates.order("updated_at DESC")
	return stuff
  end
  def limited_recent_activity(n)
	return recent_activity.slice(1,n)
  end
  
  def isAuthenticated
    return :verified
  end
  
  def cheatAuth(pass)
    return self.temp_pw == pass
  end
  
  def message_copys
    return self.received_messages
  end
  
  def questions
    return ItemTemplate.where(:user_id => self.id).where(:producible_type => 'Question')
  end
  
  def challenges
     return ItemTemplate.where(:user_id => self.id).where(:producible_type => 'Challenge')
  end
  
  def events
     return ItemTemplate.where(:user_id => self.id).where(:producible_type => 'Event')
  end
  
  def responses
    return ResponseTemplate.where(:user_id => self.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def random_string(len)
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
     newpass = ""
     1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
     return newpass
  end

  def generate_random_authlogic()
    random_length = 10
    temp = random_string(random_length)
    temp_pwd = temp
    return temp_pwd
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def create
    #picturePotential = picture_image(params[:user][:picture])
   # params[:user][:picture] = picturePotential[0].url
    puts "why dont u love me"
    puts params[:user]
    a = params[:user]
    upload = a['upload']
    a.delete('upload')
    puts "cuz you are a woman"
    @user = User.new(a)
    @user.login = a['login']
    @user.email = a['email']
    @user.location = a['location']
    @user.password = a['password']
    @user.temp_pw = @user.password
    @user.temp_pwd = generate_random_authlogic()
    if(@user.location != nil)
      a = Geocoder.coordinates(@user.location)
      @user.lat = a[0].to_s
      @user.lng = a[1].to_s
    end
    puts "WHY DONT U LOVE ME"
    puts params[:user][:picture]


    if @user.save
       if upload != nil
          picture_image(@user, upload)
        else
          @user.picture = "DEFAULT"
        end
      if params[:picture] == nil
        puts "HU HO"

      end
      puts "LE PICTURE"
     # @user.picture = picturePotential[0].url
      #@user.save
      redirect_to summary_path
    else
      puts "AHAH"
      render "new"
    end
  end

  def update
     @user = User.find(session[:user_id])

     respond_to do |format|
       if @user.update_attributes(params[:user])
         format.html { redirect_to summary_path, notice: 'Question was successfully updated.' }
         format.json { head :ok }
       else
         format.html { render action: "edit" }
         format.json { render json: @question.errors, status: :unprocessable_entity }
       end
     end
   end

  def destroy
    if not User.exists?(params[:user])
      redirect_to root_url, :notice => "User not found"
    else
      @u = User.find(params[:user])
    end
    @u.destroy
    respond_to do |format|
      format.html {redirect_to root_url, :notice => "User destroyed!"}
      format.xml {head :ok}
    end
  end

  def profile
    @user = User.find(params[:id])
   # @followed_user = current_user.followees.where(:followee_id => @user_id).size != 0
    @items = ItemTemplate.where(:user_id => params[:id]).paginate(:page => params[:page], :per_page => 15)
  end

  respond_to :json

  def recent
    @user = User.find(session[:user_id])
    redirect_to
    respond_with(@user.recent_activity)
  end

  def validate
    id = params[:user]
    val = params[:token]
    @validated = false
    if(val != nil and id != nil)
      @validated = (User.where(:id => id).first.temp_pwd == val)
      user = User.where(:id => id).first
      if @validated
         user.verified = @validated
         user.password = user.password_digest
         user.save
       end

    end
  end

  def picture_image(user, pictureed_file)
    puts "attempting to do shit with the image"
    name =  pictureed_file.original_filename

         #create the file path
        path = File.join("tmp", name)
        # write the file
       File.open(path, "wb") { |f| f.write(pictureed_file.read) }

      #a = 0 / 0
      item = Fleakr.upload(path)
      user.picture = "DEFAULT"
      if item != nil
        if item[0] != nil
          user.picture = item[0].url
        end
      end
     user.save
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_tag sessions_path do %>
    <label>Your login</label>
    <%= text_field_tag :login, params[:login], :size => 18, :id=>'username', :class=>'span3' %>
    <label>Your password</label>
    <%= password_field_tag :password, nil, :size => 18, :id=>'password_password', :class=>'span3' %>

    <br>
      <%= submit_tag "Sign in", :class => 'btn' %>


<% end %>

app/views/users/_register.html.erb
<script type="text/javascript">
$(document).ready( function() {
var input = document.getElementsByName('user[location]')[0];
var autocomplete = new google.maps.places.Autocomplete(input, options);
}
</script>

<%= form_for @user, :action => :create, :controller => :users do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<label>Your desired username</label>
   <%= f.text_field :login, :size => 18, :id=>'username_input', :class=>'span3', :placerholder=>'username' %>
  <br>
   <label>Your email address</label>
   <%= f.email_field :email, :size => 18, :id=>'email_input', :class=>'span3', :placeholder => 'email' %>
     <label>Your password</label>
   <%= f.password_field :password, :size => 18, :id=>'password_password', :class=>'span3', :placeholder => 'password' %>
 <label>Confirm password</label>
   <%= f.password_field :password_confirmation, :size => 18, :id=>'re_password_password', :class=>'span3', :placeholder =>'re-enter password' %>
    <label>Default location</label>
   <%= f.text_field :location, :size => 18, :id=>'location_input', :class=>'span3', :placeholder=>'enter location' %>
<label>Profile Picture</label>
   <%= f.file_field :upload, :id=> 'upload_input', :class=>'span3', :placeholder=>'' %>
<br>
<br>

<br>
      <%= submit_tag 'register', :class => 'btn' %>


<% end %>

app/views/users/edit.html.erb
<script src="//maps.googleapis.com/maps/api/js?sensor=false&libraries=places"
      type="text/javascript"></script>
<script type="text/javascript">
$.fn.center = function (top_offset) {
	window_width =  $(window).width() > 500 ? $(window).width() : 500;
    this.css("position","absolute");
	this.css("top", ($('.splash_box').position().top + top_offset - 20)  + 'px');
    this.css("left", ((window_width - this.outerWidth()) / 2) + $(window).scrollLeft() + "px");
    return this;
}
$(window).load(function() {
	center_elements();
	
	$(window).resize(function() {
		center_elements();
	});
	
	function center_elements() {
		window_height =  $(window).height() > 700 ? $(window).height() : 700;
		window_width =  $(window).width() > 500 ? $(window).width() : 500;
		$('.splash_box').center();
	   	$('.splash_box').css("top", ((window_height - $('.splash_box').outerHeight()) / 2) + "px");
		$('.username').center(90);
		$('.email').center(200);
		$('.password').center(310);
		$('.re_password').center(420);
		$('.location').center(530)
		$('#links').center(650);
		
		$('#username_input').center(120);
		$('#email_input').center(230);
		$('#password_input').center(340);
		$('#re_password_input').center(450);
		$('#password_password').center(340);
		$('#re_password_password').center(450);
		$('#password_input').center(340);
		$('#re_password_input').center(450);
		$('#location_input').center(560);
		
		$('#username_prompt').center(80);
		$('#username_prompt').css("left", ($('#username_input').position().left) + "px");
		$('#email_prompt').center(190);
		$('#email_prompt').css("left", ($('#email_input').position().left) + "px");
		$('#password_prompt').center(300);
		$('#password_prompt').css("left", ($('#password_password').position().left) + "px");
		$('#re_password_prompt').center(410);
		$('#re_password_prompt').css("left", ($('#re_password_password').position().left) + "px");
		$('#location_prompt').center(520);
		$('#location_prompt').css("left", ($('#location_input').position().left) + "px");
	}
	
	var defaultBounds = new google.maps.LatLngBounds(
	  new google.maps.LatLng(-33.8902, 151.1759),
	  new google.maps.LatLng(-33.8474, 151.2631));

	var input = document.getElementById('location_input');
	var options = {
	  bounds: defaultBounds,
	  types: ['geocode']
	};

	autocomplete = new google.maps.places.Autocomplete(input, options);
 });
</script>
<%= image_tag "../images/splash_box.png", :class=>'splash_box' %>

<div class="labels">
	<div id="username_prompt">Enter a User ID</div>
	<div id="email_prompt">Email Address</div>
	<div id="password_prompt">Password</div>
	<div id="re_password_prompt">Re-enter Password</div>
	<div id="location_prompt">Location</div>
</div>

<%= render 'form' %>

app/views/users/new.html.erb
<script type="text/javascript">
  function sign(){
}

function register(){
}
</script>

<div id="container">

    <div id="content">
      <br>
      <h1>Sign in or Register</h1>
      <br><br>
      <div class="row">
        <div class="span4 offset1 register">
          <h3>Please sign in:</h3><br>
          <%= render 'form' %>
        </div>
        <div class="span5 register">
          <h3>Please register:</h3><br>
         <%= render 'register' %>
          </form>
        </div>

      </div>
    </div>
    <br><BR><BR>
  </div>
</body>

app/views/users/profile.html.erb
<h1> <%= @user.login %>'s Profile </h1>

<% link_to "send a message" %>&nbsp;&nbsp;&nbsp; <% link_to "subscribe" %>
<div id='radical'>
 	 <ol id="list_results" class="span8">
          <br>
		  <% @items.each do |item| %>
        <li>
		    single result 
			name: <%= item["title"] %>
			description: <%= item["description"] %>
		  </li>
		  <br>
		<% end %>
		<br> <%= will_paginate @items %> SIGH
          <img src="/assets/dummy_searchnav.png">
      </ol>
  </div>

app/views/users/validate.html.erb
Hey!

Am I validated? <%= @validated %> Yayy