config/routes.rb
Citysandbox::Application.routes.draw do

  resources :betausers

  root :to => 'home#splash', :as => :home

  get "welcome/show"
  match "welcome/show" => "welcome#show"
  get 'welcome/autocomplete_category_name'
  get "questions/autocomplete_category_name"
  match 'ugh' => 'welcome#show'
  scope :as => :home do
    get  '/' => 'home#splash', :as => :splash
    get '/login' => 'sessions#new', :as => :login
    get '/logout' => 'sessions#destroy', :as => :logout
    get '/register' => 'betausers#new', :as => :betaregister
  end

  resources :sessions

  resources :categories

  resources :groups do
    get '/members' => "groups#members"
    get '/project' => "groups#project"
    get '/edit' => "groups#edit"
  end

  match '/users/validate' => 'users#validate'
  match "/vote" => "proposals#vote"
  match "/edit_profile" => "users#edit"
  match "/follow" => "discussion#follow"
  match "/unfollow" => "discussion#unfollow"
  match "/recent" => "users#recent"
  match "/qr" => 'discussion#qr'
  match "/validate" => 'users#validate'
  match "/users/profile/:id" => 'users#profile'
  match "fetch" => "discussion#filter"
  match "ugh" => "questions#auto"
  
  match '/groups/members' => "groups#members"
  match '/groups/project' => "groups#project"
  match '/groups/edit' => "groups#edit"
  
  resources :questions do
    match "/auto" => "questions#auto"
    resources :response_questions, :shallow => true
    resources :challenges, :shallow => true
    resources :events, :shallow => true
    get :auto_complete_for_category_name, :on => :collection
    get :auto_complete_category_name, :on => :collection
  end
  resources :challenges do
      get :auto_complete_for_category_name, :on => :collection
      get :auto_complete_category_name, :on => :collection
  end
  
  post "questions/auto_complete_for_category_name" => "questions#auto_complete_for_category_name"
  post "challenges/auto_complete_for_category_name" => "challenges#auto_complete_for_category_name"
  post "events/auto_complete_for_category_name" => "events#auto_complete_for_category_name"
  get "questions/autocomplete_category_name"
  get "events/autocomplete_category_name"
  get "challenges/autocomplete_category_name"

  resources :events do
    resources :response_events, :shallow => true
    get :auto_complete_for_category_name, :on => :collection
    get :auto_complete_category_name, :on => :collection
  end

  resources :discussion do
    get '/' => 'discussion#summary', :as => :summary
  end

  match 'filter' => 'discussion#filterNew'

  get '/summary' => 'discussion#summary', :as => :summary

  match "/map" => 'map#index', :as => :map
  match "/map/draw_map" => 'map#draw_map'
  match "/map/draw" => "map#draw"

  match "messages/sent" => "sent#show"
  match "messages/inbox" => "inbox#show"
  match "messages/new" => 'inbox#new'
  match "messages/create" => "inbox#create"

  match "messages/reply/:id" => "inbox#respond", :as => :reply
  match "messages/send_to/:id" => "inbox#send_to", :as => :reply

  resources :users, :messages,  :inbox

  match "questionNew" => "questions#newForm"
  match "challengeNew" => "challenges#challengeNew"
  match "eventNew" => "events#eventNew"
  match "confirm" => "map#drawMapConfirm"
  match "map2" => "map#drawMapBoxies"
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :challenge
  acts_as :item_template, :as => :producible

#  belongs_to :question
#  belongs_to :user
#  belongs_to :categories
#  belongs_to :challenge
#  attr_accessor :lat
#  attr_accessor :lng

#  validates :categories_id, :presence => true

#  has_many :response_events
#  has_many :followed_events

  scope :followed, lambda{|key| {:conditions => {:id => key}}}

  scope :has_category,       lambda{ |n| { :conditions => { :categories_id => n}}}
  scope :has_title, lambda{|name| {:conditions => ["title LIKE ? OR title LIKE ? OR title LIKE ?", "% " + name + " %", name, name + " %"]}}
  scope :keyword, lambda{|key| { :conditions => ["title LIKE ? OR title LIKE ? OR title LIKE ? OR description LIKE ? OR description LIKE ? OR description LIKE ?", "% " + key + " %", key, key + " %", "% " + key + " %", key, key + " %" ]}}

  #before_save :upkeep

  def category_id
     return categories_id
  end

  def generate_content
  return {"time"=>time, "challenge_id"=>challenge_id, "minimum_to_run"=>minimum_to_run}
  end

  def create_followed
    followed = FollowedEvent.new
    followed.user_id = current_user.id
    followed.event_id = id
    followed.save
  end

  def create_followed(follower)
    followed = FollowedEvent.new
    followed.user_id = follower.id
    followed.event_id = id
    if FollowedEvent.where(:event_id => id).where(:user_id => follower.id) == []
      followed.save
    end
  end

  def most_popular(since_last)
    return Question.where("updated_at > '#{since_last}'").where()
  end

  def remove_followed
     followed = followed_events
     a= followed.where(:user_id => current_user.id).first
     return a.destroy
   end

   def remove_followed(follower)
     followed = followed_events
     a = followed.where(:user_id => follower.id).first
     return a.destroy
   end

   def fetch_location
     @events_table = ENV['csb_locations']
     return ::FT.execute "SELECT Location FROM #{@events_table} WHERE ID = #{id} AND Origin = 'events'"
   end

   def update_location(loc)
     @events_table = ENV['csb_locations']
     @quest_dummy = ::FT.execute "SELECT rowid FROM #{@events_table} WHERE ID = #{id} AND Origin = 'events'"
     if @quest_dummy[0] == nil
       return insert_location(loc)
     end
     @rowid = @quest_dummy[0][:rowid]

     return ::FT.execute "UPDATE #{@events_table} SET Location='#{loc}' WHERE ROWID = '#{@rowid}' AND Origin = 'events'"
   end

   def insert_location(loc)
     @events_table = ENV['csb_locations']
     return ::FT.execute "INSERT INTO #{@events_table} (Location, ID, Origin, Category) VALUES ('#{loc}', #{id}, 'events', #{categories_id})"
   end


   def grab_nearest(number)
     @events_table = ENV['csb_locations']
     @loc_x = location.split[0].to_f
     @loc_y = location.split[1].to_f
     return ::FT.execute "SELECT * FROM #{@events_table} WHERE Origin = 'events' ORDER BY ST_DISTANCE(Location, LATLNG(#{@loc_x},#{@loc_y})) LIMIT #{number}"
   end

    def retrieve_google(db_return)
       rtn = []
       db_return.each do |x|
         rtn += [x[:id]]
       end
       return Event.followed(rtn)
     end


    def most_popular(since_last, distance, target_location)
       set =  Event.where("updated_at > '#{since_last}'").order("popularity DESC")
       google_set = grab_circle(distance, target_location, 25)
       google_fetch = retrieve_google(google_set)
       return google_fetch.where("updated_at > '#{since_last}'").order("popularity DESC")
     end

      def sift_circle(distance, target_loc, number, set)
         circles = grab_circle(distance, target_loc, number)
         circles = retrieve_google_with_set(set, circles)
         return circles
       end

       def retrieve_google_with_set(set, db_return)
         rtn = []
         db_return.each do |x|
           rtn += [x[:id]]
         end
         return set.followed(rtn)
       end
     	def user
     	  ItemTemplate.where(:user_id => self.user_id).where(:producible_id => self.id)
       end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events/1
  # GET /events/1.json
   autocomplete :category, :name
  def show
    @sample = Event.all.pop
     @samples = @sample.kludgy_related_similar()
     @different_samples = sample.kludgy_related_other()
    if current_user == nil
      redirect_to home_login_url
    else
      @event = Event.find(params[:id])
      @category = Categories.find(@event.categories_id)\
    
      @followed = current_user.followed_events.where(:event_id => params[:id]).size != 0
      @followed_user = current_user.followed_users.where(:followed_user_id => @event.user_id).size != 0

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @event }
      end
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
@category = Category.new
@sample = Question.all.pop
@samples = @sample.kludgy_related_similar()
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  def eventNew
  @event = Event.new 
  @category = Category.new
  @sample = Question.all.pop
  @samples = @sample.kludgy_related_similar()
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    puts "GET IT SON"
    puts params
    puts "YOU AND ME AGAINST THE WORLD"
    puts params[:category]
    puts "CATEGRY"
    @event = Event.new(params[:event])
    @event.challenge_id = params[:challenge_id]
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        @temp = Geocoder.coordinates(@event.location)
        @event.lat = @temp[0].to_s
        @event.lng = @temp[1].to_s
        @event.insert_location(@event.lat + ', ' + @event.lng)
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<script src="//maps.googleapis.com/maps/api/js?sensor=false&libraries=places"
      type="text/javascript"></script>
<script type="text/javascript">
$(document).ready( function() {
  var map;
    var myOptions = {
      zoom: 8,
      center: new google.maps.LatLng(37.87159260,-122.2727470), // Berkeley, CA
      mapTypeId: google.maps.MapTypeId.ROADMAP
  };
    map = new google.maps.Map(document.getElementById('form_map_canvas'), myOptions);

  var defaultBounds = new google.maps.LatLngBounds(
    new google.maps.LatLng(-33.8902, 151.1759),
    new google.maps.LatLng(-33.8474, 151.2631));

  var input = document.getElementById('question_location');
  var options = {
    bounds: defaultBounds,
    types: ['geocode']
  };

  autocomplete = new google.maps.places.Autocomplete(input, options);

  if ($('#event_location').val() != '') {
    center_map(map);
  }

  $('#event_location').blur( function() {
    center_map(map);
  });

});

function center_map(map) {
  var geocoder = new google.maps.Geocoder();
  var address = $.trim(address = $('#event_location').val().replace(/[\t\n\r]/gi, ""));
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          map.setCenter(results[0].geometry.location);
          var marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location
          });
      $('#event_lat').attr('value', results[0].geometry.location.lat());
      $('#event_lng').attr('value', results[0].geometry.location.lng());
        }
  });
}
</script>
<%= form_for(@event) do |c| %>
<%= c.hidden_field :lat %>
<%= c.hidden_field :lng %>
	  <p>
	    <%= c.label :title, "Title" %>
		<br>
	    <%= c.text_field :title %>
	  </p>
	  <p>
	    <%= c.label :description, "Description" %>
		<br>
	    <%= c.text_area :description, :rows=>3 %>
	  </p>
	  <p>
		<%= c.label :location %>
		<br>
		<%= c.text_area :location, :rows=>2 %>
		  <div id="form_map_canvas"></div>
	  </p>
	  <p>
	    <%= c.label :time, "Time" %><br />
	    <%= c.datetime_select :time %>
	  </p>
	<p>
    	<%= c.label :threshold , "Threshold" %>
		<br>
	    <%= c.text_area :minimum_to_run, :rows => 1 %>
	</p>
	  <p>
		<%= c.label 'Categories: ' %>
		<br>
			<%= submit_tag 'Create Your Event', :class => 'btn' %>
		  	<%= form_tag("/categories", :method => 'post') do %>
		 <% autocomplete_field_tag 'category', '', events_autocomplete_category_name_path, :size => 75 %>
			<% end %>
		<br>
	  </p>

	  <p>
	 
	  </p>
	
<% end %>

app/views/events/edit.html.erb
<script type="text/javascript">
$.fn.center = function (top_offset) {
	window_width =  $(window).width() > 500 ? $(window).width() : 500;
    this.css("position","absolute");
	this.css("top", ($('.splash_box').position().top + top_offset)  + 'px');
    this.css("left", ((window_width - this.outerWidth()) / 2) + $(window).scrollLeft() + "px");
    return this;
}
$(window).load(function() {
	$(window).resize(function() {
		$('#content').css('margin-left', ($(window).width()-$('#content .splash_box').width())/2 + 'px');
		$('.form').center(10);
	});
	$('#content').css('margin-top', '10px');
	$('#content').css('margin-left', ($(window).width()-$('#content .splash_box').width())/2 + 'px');
	$('.form').center(10);
});
</script>
<style type="text/css">
html {
        background: url('../../images/splash_background.png') no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
}
</style>
<div id='content'>
<%= image_tag "../images/splash_box.png", :class=>'splash_box' %>
<div class='form'>
<%= render 'form' %>

</div>
</div>

app/views/events/eventNew.html.erb
<script type="text/javascript">
  var map;
  var autocomplete;
 var myBoxValue = "Berkeley, CA";
 var boxes;
var autocomplete2;
$(document).ready( function() {
 boxes = new Array();

 boxes.push('mainBox');

  boxes.push('box1');
  $('mainBox').bind('onchange', setBoxes(document.getElementById('mainBox').value));
  $('box1').bind('onchange', setBoxes(document.getElementById('box1').value));
  $('mainBox').bind('onpropertychange', setBoxes(document.getElementById('mainBox').value));
  $('box1').bind('onpropertychange', setBoxes(document.getElementById('box1').value));

    var myOptions = {
      zoom: 8,
      center: new google.maps.LatLng(37.87159260,-122.2727470), // Berkeley, CA
      mapTypeId: google.maps.MapTypeId.ROADMAP
  };
    map = new google.maps.Map(document.getElementById('form_map_canvas'), myOptions);

  var defaultBounds = new google.maps.LatLngBounds(
    new google.maps.LatLng(-33.8902, 151.1759),
    new google.maps.LatLng(-33.8474, 151.2631));

  var input = document.getElementById('question_location');
  var options = {
    bounds: defaultBounds,
    types: ['geocode']
  };
  autocomplete = new google.maps.places.Autocomplete(input);
  autocomplete.bindTo('bounds', map);
  var addAuto = new google.maps.places.Autocomplete(document.getElementById('mainBox'));
  var auto2 = new google.maps.places.Autocomplete(document.getElementById('box1'));
  if ($('#question_location').val() != '') {
    center_map(map);
  }

  $('#question_location').blur( function() {
    center_map(map);
  });

});

 function setBoxes(newVal)
{
   var temp = new Array();

  for(var i=0; i<2; i++);
   {
    var a = boxes.pop();
    temp.push(a);
    document.getElementById(a).value = newVal;
    }

 for(var k=0; k<2; k++);
   {
    var a = temp.pop();
    boxes.push(a);
    }

}

function adjust_location(box)
{

}

function center_map(map) {
  var geocoder = new google.maps.Geocoder();
  var address = $.trim(address = $('#question_location').val().replace(/[\t\n\r]/gi, ""));
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          map.setCenter(results[0].geometry.location);
          var marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location
          });
      $('#question_lat').attr('value', results[0].geometry.location.lat());
      $('#question_lng').attr('value', results[0].geometry.location.lng());
        }
  });
}

</script>
  <div id="container">

    <div id="content">
      <br>
      <h1>Organize an Event</h1>
      <br><br>
        <div class="row span6 question_form">
            <h3>I want to ask about...</h3><br>

    		<%= render 'form' %>
        </div>
        <div class="span5">
            <h3> Sample events asked in <input name="box1" id="box1" type="text" class="span2" placeholder="Berkeley, CA"/> </h3>
          <ul class="related_list unstyled">
           		<% @samples.each do |sample| %>
	            <li class="row">
	              <a href="#" >
	              <img src="http://placehold.it/98x50" class="span2" align="left" />
	              </a>
	              <div class="span3">
	              <h4><%= sample.title %></h4>
	             Description: <%= sample.description %>
	              </div>
	            </li>
				<% end %>
          </ul>
        </div>

    </div>
  </div>

app/views/events/show.html.erb
<script type="text/javascript">
$(document).ready( function() {
	$('#tabs ul').idTabs();
	
	var map;
    var myOptions = {
    	zoom: 14,
    	center: new google.maps.LatLng(37.87159260,-122.2727470), // Berkeley, CA
    	mapTypeId: google.maps.MapTypeId.ROADMAP
	};
   	map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);

    var geocoder = new google.maps.Geocoder();
	var address = '<%= @event.location %>';
	    geocoder.geocode( { 'address': address}, function(results, status) {
	      if (status == google.maps.GeocoderStatus.OK) {
	        map.setCenter(results[0].geometry.location);
	        var marker = new google.maps.Marker({
	            map: map,
	            position: results[0].geometry.location,
				icon: '../images/event_map_icon.png'
	        });
	      } else {
	        //alert("Geocode was not successful for the following reason: " + status);
	      }
	});
	$('#QR').attr('href', 'https://chart.googleapis.com/chart?chs=150x150&cht=qr&chl=<%=event_url(@event)%>&choe=UTF-8');
	$('#share').attr('href', 'mailto:?subject=[City%20Sandbox]%20<%= current_user.login%>%20has%20shared%20a%20link%20with%20you!&body=<%=event_url(@event)%>');
	
	$('#unfollow_user').click(function(){
		var params = {};
		params['item_to_follow'] = '<%= @event.user.id %>';
		params['type'] = 'User';
		$.get('/unfollow', params);
		$('#unfollow_user').hide();
		$('#follow_user').show();
	});
	
	$('#follow_user').click(function(){
		var params = {};
		params['item_to_follow'] = '<%= @event.user.id %>';
		params['type'] = 'User';
		$.get('/follow', params);
		$('#follow_user').hide();
		$('#unfollow_user').show();
	});
	
	$('#unfollow').click(function(){
		var params = {};
		params['item_to_follow'] = '<%= @event.id %>';
		params['type'] = 'Event';
		$.get('/unfollow', params);
		$('#unfollow').hide();
		$('#follow').show();
	});
	
	$('#follow').click(function(){
		var params = {};
		params['item_to_follow'] = '<%= @event.id %>';
		params['type'] = 'Event';
		$.get('/follow', params);
		$('#follow').hide();
		$('#unfollow').show();
	});
	
	if ('<%= @followed %>' == 'true') {
		$('#follow').hide();
	} else {
		$('#unfollow').hide();
	}
	if ('<%= @followed_user %>' == 'true') {
		$('#follow_user').hide();
	} else {
		$('#unfollow_user').hide();
	}
	
	$(window).resize(function() {
		$('#content').css('margin-left', ($(window).width()-960)/2 + 'px');
		$('#icon_title').css('margin-left', ($(window).width()-960)/2 + 'px');
		$('#user_nav').css('margin-right', ($(window).width()-960)/2 + 'px');
		$('#header_tabs').css('margin-left', ($(window).width()-960)/4 + 'px');
	});
	$('#content').css('margin-left', ($(window).width()-960)/2 + 'px');
	$('#icon_title').css('margin-left', ($(window).width()-960)/2 + 'px');
	$('#user_nav').css('margin-right', ($(window).width()-960)/2 + 'px');
	$('#header_tabs').css('margin-left', ($(window).width()-960)/4 + 'px');
	
	$('.iframe').fancybox({
		'width' : 320,
		'height' : 350,
		'autoscale': false,
		'autoDimensions': false,
		'titlePosition': 'outside',
		'titleFormat': formatTitle
	});	
	$('#fancybox-wrap').click(function () {
		printIframe('fancybox-frame');
	});
});
function printIframe(id)
{
    frames[0].print();
}
function formatTitle() {
    return '<div id="print"><a href="javascript:;"><img src="../images/print.png" title="Print QR Code."></a></div>';
}
</script>
<style type="text/css">
</style>
<div id='content'>
<div id='user_sidebar'>
	<b>About <a href='/users/profile/<%= @event.user.id %>' class='black_link'><%= @event.user.login %></a> </b>
	<br>
	<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'100x100', :alt => "User avatar" %>
	<%= @event.user.picture %> 
	<br>
	<b>Joined:</b> <%= @event.user.created_at.strftime("%Y %b %d")%>
	<br>
	<b>Questions:</b> <%= @event.user.questions.length %>
	<br>
	<b>Responses:</b> <%= @event.user.response_questions.length + @event.user.response_challenges.length + @event.user.response_events.length %>
	<br>
	<b>Challenges:</b> <%= @event.user.challenges.length %>
	<br>
	<br>
	<!--<b><%= link_to 'Recent Activity', summary_path, :class=>'black_link' %></b>
	<br>-->
	<b><a href='/messages/send_to/<%=@event.user.id%>' class='black_link'>Send Message</a></b>
	<br>
	<b><a href='javascript:;' id='unfollow_user' class='black_link'>Unfollow</a></b>
	<b><a href='javascript:;' id='follow_user' class='black_link'>Follow</a></b>
</div>
<div id='main_question_content'>
<div class='event_main'>
	<span id='question_map'>
		<div id="map_canvas"></div>
		<%=h @event.location %>
	</span>
	<span id='question_title_display'>
		<b><%= @event.title %></b>
	</span>
	<br>
	<br>
	<span id='question_author'>
		<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'30x30', :alt => "User avatar" %>
		<%=h @event.user.picture %> by <%= @event.user.login %> |
		<%= @event.created_at.strftime("%Y %b %d") %> | <%= @category.category %> |
		<a href='javascript:;' id='unfollow' class='black_link'>Unfollow | </a> 
		<a href='javascript:;' id='follow' class='black_link'>Follow | </a>
		<a class='black_link' id='share'> Share </a>|
		<%= link_to 'QR', qr_url(:format=>event_url(@event), :title=>@event.title), :class=>'iframe black_link'%>
	</span>
	<br>
	<br>
	<div id='form_links'>
	<ul>
	<li><a href="#response_form" class="black_link">Add Response</a></li>
	</ul>
	</div>
</div>
<% if @event.description.length > 0 %>
	<br>
	<div class='event_main'>
		<span id='question_description'>
			<%= @event.description %> 
		</span>
	</div>
<% end %>
<br>
<div class='question_main' style='min-height:150px; padding: 0'>
	<div class='entry_author'>
		<% if @event.challenge.question.anonymous == 1 %>
			<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'60x60', :alt => "User avatar" %>
			<%=h @event.challenge.question.user.picture %> 
			<br>
			Anonymous
			<br>
		<% else %>
			<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'60x60', :alt => "User avatar" %>
			<%=h @event.challenge.question.user.picture %> 
			<br>
			<%=h @event.challenge.question.user.login %>
			<br>
		<% end %>
		<%= @event.challenge.question.created_at.strftime("%Y %b %d") %>
		<br>
	</div>
	<div class='entry_title' >
		<b><%= link_to @event.challenge.question.title, @event.challenge.question, :class=>'black_link' %></b>
	</div>
	<br>
</div>
<br>
<div class='challenge_main' style='min-height:150px; padding:0'>
	<div class='entry_author'>
		<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'60x60', :alt => "User avatar" %>
		<%=h @event.challenge.user.picture %> 
		<br>
		<%=h @event.challenge.user.login %>
		<br>
		<%= @event.challenge.created_at.strftime("%Y %b %d") %>
		<br>
	</div>
	<div class='entry_title'>
		<b><%= link_to @event.challenge.title, @event.challenge, :class=>'black_link' %></b>
	</div>	
	<br>
	<div class='latest_response'>
	    <%=h @event.challenge.description %>
		<div id='challenge_dates'>
		<ul>
			<li><b> Submission Deadline: </b> <%= @event.challenge.submission_deadline.strftime("%Y %b %d") %> </li>
			<li><b> Vote Deadline: </b> <%= @event.challenge.vote_deadline.strftime("%Y %b %d") %> </li>
		</ul>
		</div>
	</div>
</div>
<br>
<div id='tabs'>
<br>
<div id='tabs_menu'>	
<ul>
	<li><b><a href="#responses">Responses</a></b></li>
</ul>
</div>
<div id='responses'>
<div class='tab_body'>
	<% @event.response_events.reverse_each do |r| %>
	<div class='individual response_individual'>
			<% if r.anonymous == 1 %>
				<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'30x30', :alt => "User avatar" %>
				<%=h r.user.picture %> 
				Anonymous | 
			<% else %>
				<%= image_tag "../images/default_avatar.png", :class=>'user_avatar', :size=>'30x30', :alt => "User avatar" %>
				<%=h r.user.picture %> 
				<%=h r.user.login %> |
			<% end %>
			<%= time_ago_in_words(r.created_at) %> ago 
			<div class='latest_response'>
			    <%=h r.response %>
			</div>
		<br>
		<hr>
	</div>
	<% end %>
	<div id='response_form' class='individual_form'> 
		Add Response
		<br>
		<%= form_for([@event, ResponseEvent.new]) do |r| %>
		    <%= r.text_area :response, :rows => 3 %>
			<br>
			<%= r.check_box :anonymous %>
			<%= r.label 'Post anonymously' %>
			<br>
		    <%= r.submit "Submit" %>
		<% end %>
	</div>
</div>
</div>
<br>
<% if @event.user == current_user %>
	<%= link_to 'Edit', edit_event_path(@event), :class=>'black_link' %> |
<% end %>
<%= link_to 'Back To Summary', summary_path, :class=>'black_link' %>
</div>
</div>
</div>